variables:
    FDO_UPSTREAM_REPO:  'xorg/driver/xf86-video-geode'

include:
    - local:    '.gitlab-ci/common/xorg-driver.yml'

# This driver is 32bit only, as this GPU only exists on 32bit SoCs
build@debian@amd64:
    script:
        - echo "This driver cannot be built on 64bit"
    rules:
        - when: never
